steps:
  # Build and push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/language-learning-backend', '-f', 'Dockerfile.prod', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/language-learning-backend']

  # Build and push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/language-learning-frontend', '-f', 'frontend/Dockerfile.prod', './frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/language-learning-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'language-learning-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/language-learning-backend'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--clear-env-vars'
      - '--clear-secrets'
      - '--update-secrets'
      - 'DATABASE_URL=database_url:latest'
      - '--update-secrets'
      - 'DATABASE_USER=database_user:latest'
      - '--update-secrets'
      - 'DATABASE_PASSWORD=database_password:latest'
      - '--update-secrets'
      - 'JWT_SECRET=jwt_secret:latest'
      - '--update-secrets'
      - 'FRONTEND_URL=frontend_url:latest'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'language-learning-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/language-learning-frontend'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'

images:
  - 'gcr.io/$PROJECT_ID/language-learning-backend'
  - 'gcr.io/$PROJECT_ID/language-learning-frontend'

substitutions:
  _REGION: 'europe-central2'