spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/language_learning
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.3
          max-tokens: 500
  autoconfigure:
    exclude: []

server:
  port: 8080

logging:
  level:
    org.springframework.ai: DEBUG
    com.example.languagelearning.service.AiGrammarValidationService: DEBUG 